import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";
import Header from "@/app/components/header/Header";


export const metadata: Metadata = {
  title: 'ChangMin Mall',
  description: 'Generated by ChangMin',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
    <body>
      <Header/>
      {children}
    </body>
    </html>
  )
}
